apiVersion: v1
kind: PersistentVolume
metadata:
  name: webben-nfs
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nolock
  nfs:
    server: 10.128.55.167
    path: "/exports/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: webben-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
